/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HubRouteImport } from './routes/hub'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadSplatRouteImport } from './routes/read.$'

const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadSplatRoute = ReadSplatRouteImport.update({
  id: '/read/$',
  path: '/read/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/glossary': typeof GlossaryRoute
  '/guide': typeof GuideRoute
  '/hub': typeof HubRoute
  '/library': typeof LibraryRoute
  '/patterns': typeof PatternsRoute
  '/resources': typeof ResourcesRoute
  '/sources': typeof SourcesRoute
  '/templates': typeof TemplatesRoute
  '/toolkit': typeof ToolkitRoute
  '/read/$': typeof ReadSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/glossary': typeof GlossaryRoute
  '/guide': typeof GuideRoute
  '/hub': typeof HubRoute
  '/library': typeof LibraryRoute
  '/patterns': typeof PatternsRoute
  '/resources': typeof ResourcesRoute
  '/sources': typeof SourcesRoute
  '/templates': typeof TemplatesRoute
  '/toolkit': typeof ToolkitRoute
  '/read/$': typeof ReadSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/glossary': typeof GlossaryRoute
  '/guide': typeof GuideRoute
  '/hub': typeof HubRoute
  '/library': typeof LibraryRoute
  '/patterns': typeof PatternsRoute
  '/resources': typeof ResourcesRoute
  '/sources': typeof SourcesRoute
  '/templates': typeof TemplatesRoute
  '/toolkit': typeof ToolkitRoute
  '/read/$': typeof ReadSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculator'
    | '/dashboard'
    | '/glossary'
    | '/guide'
    | '/hub'
    | '/library'
    | '/patterns'
    | '/resources'
    | '/sources'
    | '/templates'
    | '/toolkit'
    | '/read/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculator'
    | '/dashboard'
    | '/glossary'
    | '/guide'
    | '/hub'
    | '/library'
    | '/patterns'
    | '/resources'
    | '/sources'
    | '/templates'
    | '/toolkit'
    | '/read/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculator'
    | '/dashboard'
    | '/glossary'
    | '/guide'
    | '/hub'
    | '/library'
    | '/patterns'
    | '/resources'
    | '/sources'
    | '/templates'
    | '/toolkit'
    | '/read/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorRoute: typeof CalculatorRoute
  DashboardRoute: typeof DashboardRoute
  GlossaryRoute: typeof GlossaryRoute
  GuideRoute: typeof GuideRoute
  HubRoute: typeof HubRoute
  LibraryRoute: typeof LibraryRoute
  PatternsRoute: typeof PatternsRoute
  ResourcesRoute: typeof ResourcesRoute
  SourcesRoute: typeof SourcesRoute
  TemplatesRoute: typeof TemplatesRoute
  ToolkitRoute: typeof ToolkitRoute
  ReadSplatRoute: typeof ReadSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$': {
      id: '/read/$'
      path: '/read/$'
      fullPath: '/read/$'
      preLoaderRoute: typeof ReadSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorRoute: CalculatorRoute,
  DashboardRoute: DashboardRoute,
  GlossaryRoute: GlossaryRoute,
  GuideRoute: GuideRoute,
  HubRoute: HubRoute,
  LibraryRoute: LibraryRoute,
  PatternsRoute: PatternsRoute,
  ResourcesRoute: ResourcesRoute,
  SourcesRoute: SourcesRoute,
  TemplatesRoute: TemplatesRoute,
  ToolkitRoute: ToolkitRoute,
  ReadSplatRoute: ReadSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
