/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/guide': typeof GuideRoute
  '/patterns': typeof PatternsRoute
  '/resources': typeof ResourcesRoute
  '/sources': typeof SourcesRoute
  '/templates': typeof TemplatesRoute
  '/toolkit': typeof ToolkitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/guide': typeof GuideRoute
  '/patterns': typeof PatternsRoute
  '/resources': typeof ResourcesRoute
  '/sources': typeof SourcesRoute
  '/templates': typeof TemplatesRoute
  '/toolkit': typeof ToolkitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/guide': typeof GuideRoute
  '/patterns': typeof PatternsRoute
  '/resources': typeof ResourcesRoute
  '/sources': typeof SourcesRoute
  '/templates': typeof TemplatesRoute
  '/toolkit': typeof ToolkitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculator'
    | '/dashboard'
    | '/guide'
    | '/patterns'
    | '/resources'
    | '/sources'
    | '/templates'
    | '/toolkit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculator'
    | '/dashboard'
    | '/guide'
    | '/patterns'
    | '/resources'
    | '/sources'
    | '/templates'
    | '/toolkit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculator'
    | '/dashboard'
    | '/guide'
    | '/patterns'
    | '/resources'
    | '/sources'
    | '/templates'
    | '/toolkit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorRoute: typeof CalculatorRoute
  DashboardRoute: typeof DashboardRoute
  GuideRoute: typeof GuideRoute
  PatternsRoute: typeof PatternsRoute
  ResourcesRoute: typeof ResourcesRoute
  SourcesRoute: typeof SourcesRoute
  TemplatesRoute: typeof TemplatesRoute
  ToolkitRoute: typeof ToolkitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorRoute: CalculatorRoute,
  DashboardRoute: DashboardRoute,
  GuideRoute: GuideRoute,
  PatternsRoute: PatternsRoute,
  ResourcesRoute: ResourcesRoute,
  SourcesRoute: SourcesRoute,
  TemplatesRoute: TemplatesRoute,
  ToolkitRoute: ToolkitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
